// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectEF;

#nullable disable

namespace projectEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectEF.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("71c3ac95-768d-4d95-bff8-e523f2a37201"),
                            Nombre = "Tareas Personbales",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("71c3ac95-768d-4d95-bff8-e523f2a37202"),
                            Nombre = "Tareas Laborales",
                            Peso = 20
                        });
                });

            modelBuilder.Entity("projectEF.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareId = new Guid("71c3ac95-768d-4d95-bff8-e523f2a37210"),
                            CategoriaId = new Guid("71c3ac95-768d-4d95-bff8-e523f2a37201"),
                            FechaCreacion = new DateTime(2023, 8, 6, 22, 6, 10, 585, DateTimeKind.Local).AddTicks(6726),
                            PrioridadTarea = 0,
                            Titulo = "Ir GYM"
                        },
                        new
                        {
                            TareId = new Guid("71c3ac95-768d-4d95-bff8-e523f2a37211"),
                            CategoriaId = new Guid("71c3ac95-768d-4d95-bff8-e523f2a37202"),
                            FechaCreacion = new DateTime(2023, 8, 6, 22, 6, 10, 585, DateTimeKind.Local).AddTicks(6744),
                            PrioridadTarea = 2,
                            Titulo = "Presentar API"
                        });
                });

            modelBuilder.Entity("projectEF.Models.Tarea", b =>
                {
                    b.HasOne("projectEF.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("projectEF.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
